# Generated by Django 5.2.1 on 2025-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
    ]
